Repository wecode-bootcamp-korea/30-westagram-backend-2-team, pull requests merged in 2022-02, with the labels that each got.

#1 [윤명국] Mission1 : Django 초기 세팅
  students/myungkookyoon/.gitignore
  students/myungkookyoon/manage.py
  students/myungkookyoon/requirments.txt
  students/myungkookyoon/westagram/__init__.py
  students/myungkookyoon/westagram/asgi.py
  students/myungkookyoon/westagram/settings.py
  students/myungkookyoon/westagram/urls.py
  students/myungkookyoon/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#6 [김은지] Mission 1 : Django 초기 세팅
  students/kimeunji/westagram/.gitignore
  students/kimeunji/westagram/manage.py
  students/kimeunji/westagram/requirements.txt
  students/kimeunji/westagram/westagram/__init__.py
  students/kimeunji/westagram/westagram/asgi.py
  students/kimeunji/westagram/westagram/settings.py
  students/kimeunji/westagram/westagram/urls.py
  students/kimeunji/westagram/westagram/wsgi.py
Labels: 완료

#4 [이예솔] Mission 2: 모델링
  students/yesol/westagram/users/__init__.py
  students/yesol/westagram/users/admin.py
  students/yesol/westagram/users/apps.py
  students/yesol/westagram/users/migrations/0001_initial.py
  students/yesol/westagram/users/migrations/__init__.py
  students/yesol/westagram/users/models.py
  students/yesol/westagram/users/tests.py
  students/yesol/westagram/users/views.py
  students/yesol/westagram/westagram/settings.py
Labels: 완료

#5 [윤명국] Mission 2: 모델링
  students/myungkookyoon/users/__init__.py
  students/myungkookyoon/users/admin.py
  students/myungkookyoon/users/apps.py
  students/myungkookyoon/users/migrations/__init__.py
  students/myungkookyoon/users/models.py
  students/myungkookyoon/users/tests.py
  students/myungkookyoon/users/views.py
Labels: 완료

#8 [김동규] Mission 2 : 모델링
  students/donggyu/users/__init__.py
  students/donggyu/users/admin.py
  students/donggyu/users/apps.py
  students/donggyu/users/migrations/0001_initial.py
  students/donggyu/users/migrations/__init__.py
  students/donggyu/users/models.py
  students/donggyu/users/tests.py
  students/donggyu/users/urls.py
  students/donggyu/users/views.py
  students/donggyu/westagram/settings.py
Labels: 완료

#7 [김은지] Mission 2: 모델링
  students/kimeunji/westagram/users/__init__.py
  students/kimeunji/westagram/users/admin.py
  students/kimeunji/westagram/users/apps.py
  students/kimeunji/westagram/users/migrations/__init__.py
  students/kimeunji/westagram/users/models.py
  students/kimeunji/westagram/users/tests.py
  students/kimeunji/westagram/users/views.py
Labels: 완료

#10 [김동규] Mission 3 : 회원가입 기능 구현
  students/donggyu/users/urls.py
  students/donggyu/users/views.py
  students/donggyu/westagram/urls.py
Labels: 완료

#9 [이예솔] Mission 3: 회원가입 기능 구현
  students/yesol/westagram/users/urls.py
  students/yesol/westagram/users/views.py
  students/yesol/westagram/westagram/urls.py
Labels: 완료

#12 [김동규] Mission 4 : 로그인 기능 구현
  students/donggyu/users/urls.py
  students/donggyu/users/views.py
Labels: 완료

#15 [김은지] Mission 3: 회원가입 기능 구현
  students/kimeunji/westagram/manage.py
  students/kimeunji/westagram/users/apps.py
  students/kimeunji/westagram/users/migrations/0001_initial.py
  students/kimeunji/westagram/users/models.py
  students/kimeunji/westagram/users/tests.py
  students/kimeunji/westagram/users/urls.py
  students/kimeunji/westagram/users/views.py
  students/kimeunji/westagram/westagram/asgi.py
  students/kimeunji/westagram/westagram/settings.py
  students/kimeunji/westagram/westagram/urls.py
  students/kimeunji/westagram/westagram/wsgi.py
Labels: 완료

#14 [윤명국] Mission 4: 로그인 기능 구현
  students/myungkookyoon/requirments.txt
  students/myungkookyoon/users/urls.py
  students/myungkookyoon/users/views.py
Labels: 완료

#13 [이예솔] Mission 4: 로그인 기능 구현
  students/yesol/westagram/users/urls.py
  students/yesol/westagram/users/views.py
Labels: 완료

#16 [김동규] Mission 5 : 회원가입 비밀번호 암호와 적용
  students/donggyu/requirements.txt
  students/donggyu/users/views.py
Labels: 완료

#19 [김은지] Mission 4: 로그인 기능 구현
  students/kimeunji/westagram/users/urls.py
  students/kimeunji/westagram/users/views.py
Labels: 완료

#18 [윤명국] Mission 5: 회원가입 비밀번호 암호화 적용
  students/myungkookyoon/users/views.py
Labels: 완료

#17 [이예솔] Mission 5: 회원가입 비밀번호 암호화 적용
  students/yesol/westagram/users/views.py
Labels: 완료

#20 [김동규] Mission 6 : 로그인 JWT 발급
  students/donggyu/users/views.py
  students/donggyu/westagram/settings.py
Labels: 완료

#22 [김은지] Mission 5: 회원가입 비밀번호 암호화 적용
  students/kimeunji/westagram/users/views.py
Labels: 완료

#21 [윤명국] Mission 6: 로그인 JWT 발급
  students/myungkookyoon/users/views.py
  students/myungkookyoon/westagram/settings.py
Labels: 완료

#23 [이예솔] Mission 6: 로그인 JWT 발급
  students/yesol/westagram/users/urls.py
  students/yesol/westagram/users/views.py
Labels: 완료

#24 [김은지] Mission 6: 로그인 JWT 발급
  students/kimeunji/westagram/users/views.py
  students/kimeunji/westagram/westagram/settings.py
Labels: 완료

#25 [이예솔] Mission 7: 게시물 등록 기능 구현
  students/yesol/westagram/postings/__init__.py
  students/yesol/westagram/postings/admin.py
  students/yesol/westagram/postings/apps.py
  students/yesol/westagram/postings/migrations/0001_initial.py
  students/yesol/westagram/postings/migrations/__init__.py
  students/yesol/westagram/postings/models.py
  students/yesol/westagram/postings/tests.py
  students/yesol/westagram/postings/urls.py
  students/yesol/westagram/postings/views.py
  students/yesol/westagram/westagram/settings.py
  students/yesol/westagram/westagram/urls.py
Labels: 피어 리뷰 요청

#29 [김은지]Mission8 : 게시물 댓글 등록 기능 구현
  students/kimeunji/westagram/postings/migrations/0002_comment.py
  students/kimeunji/westagram/postings/models.py
  students/kimeunji/westagram/postings/urls.py
  students/kimeunji/westagram/postings/views.py
  students/kimeunji/westagram/users/utils.py
Labels: 피어 리뷰 요청
